server:
  port: 8080
  host: api.witherview.com
  url: https://api.witherview.com/

upload:
  location: /root/videos/
  img-location: /home/ubuntu/witherview_backend/profiles

ffmpeg:
  path: /root/ffmpeg_sources/ffmpeg/

task:
  queue:
    maximum-attempt-count: 5
    cpu:
      limit-percentage: 40
    thread:
      wait-milliseconds: 3000

spring:
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.33.143:3306/witherview?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  hikari:
    pool-name: SpringBootJPAHikariCP
    maximun-pool-size: 10
    connection-timeout: 10000
    validation-timeout: 10000
    max-lifetime: 580000
    connection-init-ql: set wait_timeout = 600

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://52.79.202.205:8080/auth/realms/witherview
      client:
        registration:
          witherview:
            client-id: witherview
            client-secret: ed70fa2e-c610-470f-b8d8-1f73fb33504e # config 따로 정리할 때 값 변경 필요
            scope: openid
            authorization-grant-type: password
        provider:
          witherview:
            token-uri: http://52.79.202.205:8080/auth/realms/witherview/protocol/openid-connect/token
            username-attribute: preferred_username

keycloak:
  realm: witherview
  resource: witherview
  auth-server-url: http://52.79.202.205:8080/auth


logging:
  level:
    org.hibernate: error

cloud:
  aws:
    credentials:
      access-key: AKIAZ3SKFZJOKETNMGPV
      secret-key: 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
    stack:
      auto: false
    region:
      static: ap-northeast-2
  email-server:
    url: http://0.0.0.0:8888/

application:
  bucket:
    profile: yapp-storage/profiles
    videos: yapp-storage/video